#!/usr/bin/env bash

# launches new docker container for simpleton

p=$PWD
p=${p##*/}
echo "Checking for $p updates..."
git pull
cd ../simpleton
echo "Checking for simpleton updates..."
git pull
./launch

