#!/bin/bash

# outputs: result
roll() {
local r
let 'r = RANDOM % 1000'
if [[ $r -ge 500 ]]; then
  let 'result = (1000 - 2 * r) / (r - 1000)'
else
  let 'r = 1000 - r'
  let 'result = - (1000 - 2 * r) / (r - 1000)'
fi
}

health_levels=(
  dead
  critically_wounded
  major_wounds
  minor_wounds
  perfect_health
)
enum health_levels

